version: '3.3'

services:
  compress_images:
    container_name: compress_images_container
    image: mindkosh/image_compressor
    
    build:
      context: .
      
    environment:
      BATCH_JOB_KEY: "batch_1"
      AWS_REGION: ""
      IN_BUCKET: ""
      JSON_LOCATION: ""
      OUT_BUCKET: ""
      OUT_KEY: ""
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      DIVIDE_CAMERA_WISE: ""